server:
  port: 8080
  async:
    core-pool-size: 7
    max-pool-size: 42
    queue-capacity: 11
  security:
    cors:
      headers:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      origins:
        - http://localhost:3000
    authentication:
      whitelist:
        - /public/**
        - /test/**
        - /swagger-ui/**
        - /api/v2/api-docs
      private:
        path: /private/**
        header-key: X-Api-Key
        forwarded-user-header-key: X-Forwarded-For-User
        secret-keys:
          - value: demo
            name: demo
          - value: "Let me in!"
            name: dev
          - value: "v2-secret"
            name: v2
      jwt:
        path: /api/**
        validity-in-seconds: 3600
        secret-key: "Keep it secret!"

api:
  posts:
    generator:
      lorem-ipsum:
        url: https://jaspervdj.be/lorem-markdownum/markdown.txt

logging:
  file:
    name: logs/demo.log
  level:
    root: INFO
    org.ielts.playground: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 300MB
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password:
    ttl:
      default-in-seconds: 3600
      posts-view: 7200
      posts-search: 300
      test-audio-get: 7200
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # order_inserts: true
        jpa:
          batch_size: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
