CREATE TABLE IF NOT EXISTS test_audio (
    id BIGINT NOT NULL,
    test_id BIGINT NOT NULL,
    name VARCHAR(1024) NOT NULL,
    type VARCHAR(1024) NOT NULL,
    data BLOB NOT NULL,
    PRIMARY KEY (id)
);