name: Adds all issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@latest
        with:
          project-url: https://github.com/orgs/ielts-playground/projects/1
          github-token: d85813632b2b833583a1839bbbbf7772c5359238
